config/routes.rb
KorduroyTv::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  # home routes
  root :to => "home#index"
  match 'home/add_newsletter'                       => 'home#add_newsletter'

  # blog routes
  get 'blog'                                        => 'blogs#index'
  get 'blog/rss'                                    => 'blogs#rss',              :as => 'blog_rss'
  get 'blog/:year/:slug'                            => 'blogs#show',             :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/, :as => 'main_blog'
  post 'blog/:year/:slug/comment'                   => 'blogs#comment',          :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/
  get 'blog/:year/:slug/comment'                    => 'blogs#show',             :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/
  get 'blog/:slug'                                  => 'blogs#category',         :slug => /[-a-zA-Z0-9]+/
  
  # shows routes
  resources :show_categories do
    resources :shows
  end
  get 'shows'                                       => 'shows#index'
  get 'shows/:slug'                                 => 'shows#category',         :slug => /[-a-zA-Z0-9]+/
  get 'shows/:slug/:show_slug'                      => 'shows#show',             :slug => /[-a-zA-Z0-9]+/, :show_slug => /[-a-zA-Z0-9]+/
  post 'shows/:slug/:show_slug/comment'             => 'shows#comment',          :slug => /[-a-zA-Z0-9]+/, :show_slug => /[-a-zA-Z0-9]+/
  get 'shows/:slug/:show_slug/comment'              => 'shows#show',             :slug => /[-a-zA-Z0-9]+/, :show_slug => /[-a-zA-Z0-9]+/
  post 'shows/:slug/:show_slug/rate'                => 'shows#rate',             :slug => /[-a-zA-Z0-9]+/, :show_slug => /[-a-zA-Z0-9]+/
  
  # makers routes
  get 'makers'                                      => 'makers#index'
  get 'makers/posts'                                => 'makers#index'
  get 'makers/list'                                 => 'makers#list'
  get 'makers/:slug'                                => 'makers#show',            :slug => /[-a-zA-Z0-9]+/,  :as => 'maker'
  get 'makers/:slug/blog/:year/:post_slug/:id'      => 'makers#blog',            :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/, :post_slug => /[-a-zA-Z0-9]+/, :id   => /[0-9]+/, :as => 'makers_blog'
  post 'makers/:slug/blog/:year/:post_slug/:id/comment' => 'makers#comment',     :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/, :post_slug => /[-a-zA-Z0-9]+/, :id   => /[0-9]+/
  get 'makers/:slug/blog/:year/:post_slug/:id/comment'  => 'makers#blog',        :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/, :post_slug => /[-a-zA-Z0-9]+/, :id   => /[0-9]+/
  get 'makers/:slug/rss'                            => 'makers#rss',             :slug => /[-a-zA-Z0-9]+/, :as => 'makers_rss'
  get 'makers/:slug/store'                          => 'makers#store',           :slug => /[-a-zA-Z0-9]+/
  get 'makers/:slug/store/:product'                 => 'makers#product',         :slug => /[-a-zA-Z0-9]+/, :product => /[0-9]+/
  get 'makers/:slug/gallery'                        => 'makers#gallery',         :slug => /[-a-zA-Z0-9]+/
  get 'makers/:slug/bio'                            => 'makers#bio',             :slug => /[-a-zA-Z0-9]+/
  get 'makers/category/:slug'                       => 'makers#category',        :slug => /[-a-zA-Z0-9]+/
  get 'makers/:slug/contact'                        => 'maker_contacts#new',     :slug => /[-a-zA-Z0-9]+/
  post 'makers/:slug/contact'                       => 'maker_contacts#create',  :slug => /[-a-zA-Z0-9]+/
  get 'makers/:slug/contact/thanks'                 => 'maker_contacts#thanks',  :slug => /[-a-zA-Z0-9]+/
  
  # the list routes
  resources :poll_categories do
    resources :polls
  end
  get 'the-list'                                    => 'polls#index'
  get 'the-list/:id'                                => 'polls#show',             :id   => /[0-9]+/
  post 'the-list/vote/:id'                          => 'polls#vote',             :id   => /[0-9]+/
  get 'the-list/:slug'                              => 'polls#category',         :slug => /[-a-zA-Z0-9]+/
  get 'the-list/results/:id'                        => 'polls#results',          :id   => /[0-9]+/
  post 'the-list/:id/comment'                       => 'polls#comment',          :id   => /[0-9]+/
  get 'the-list/:id/comment'                        => 'polls#show',             :id   => /[0-9]+/
  
  #store routes
  get 'store'                                       => 'stores#index'
  get 'store/:id'                                   => 'stores#show',            :id => /[0-9]+/
  get 'store/cart'                                  => 'stores#cart'

  #supporters routes
  resources :supporters, :only => [:index, :show]
  
  #cool routes
  get 'links'                                       => 'cool#index'
  
  #about routes
  get 'about'                                       => 'pages#about'
  get 'about/projects'                              => 'pages#projects'
  get 'about/big-shaka-club'                        => 'pages#club'
  get 'privacy'                                     => 'pages#privacy'
  get 'terms'                                       => 'pages#terms'
  get 'submissions'                                 => 'pages#submissions'
  get 'returns'                                     => 'pages#returns'
  get 'help'                                        => 'pages#help'
  get 'reef_x_cyrus_collab'                         => 'pages#reef_x_cyrus'
  get 'compassing'                                  => 'pages#compassing'

  #contact routes
  get 'contact'                                     => 'contacts#new'
  post 'contact'                                    => 'contacts#create'
  get 'contact/thanks'                              => 'contacts#thanks'

  #users routes
  devise_for :users do
    get 'users', :to => 'home#status', :as => :user_root
  end
  get 'status'                                      => 'home#status'
  
  #utilities routes
  get 'utilities/load_external_feeds'               => 'utilities#load_external_feeds', :constraints => {:ip => /127.0.0.1/}
  
  #makers admin : stores
  get    'makers_admin/stores'                      => 'makers_admin/stores#index'
  get    'makers_admin/stores/new'                  => 'makers_admin/stores#new'
  post   'makers_admin/stores/new_product'          => 'makers_admin/stores#new_product'
  get    'makers_admin/stores/:id/edit'             => 'makers_admin/stores#edit', :id => /[0-9]+/
  post   'makers_admin/stores/:id/update'           => 'makers_admin/stores#update', :id => /[0-9]+/
  post   'makers_admin/stores/:id/update_options'   => 'makers_admin/stores#update_options', :id => /[0-9]+/
  post   'makers_admin/stores/:id/variant/new'      => 'makers_admin/stores#new_variant', :id => /[0-9]+/
  post   'makers_admin/stores/:product_id/images'   => 'makers_admin/stores#images', :id => /[0-9]+/
  post   'makers_admin/stores/:id/variant/:variant_id/update' => 'makers_admin/stores#update_variant', :id => /[0-9]+/, :variant_id => /[0-9]+/
  delete 'makers_admin/stores/:id'                  => 'makers_admin/stores#delete', :id => /[0-9]+/
  delete 'makers_admin/stores/:product_id/images/:image_id' => 'makers_admin/stores#delete_image', :product_id => /[0-9]+/, :image_id   => /[0-9]+/
  delete 'makers_admin/stores/:product_id/variant/:variant_id' => 'makers_admin/stores#delete_variant', :product_id => /[0-9]+/, :variant_id   => /[0-9]+/
  get    'makers_admin/stores/orders'               => 'makers_admin/stores#orders'
  get    'makers_admin/stores/order/:id'            => 'makers_admin/stores#order', :id => /[0-9]+/
  
  #makers admin : images
  
  #makers admin : others
  namespace :makers_admin do
    resources :maker_photos, :maker_videos, :makers, :products
    resources :blogs do
      get 'reblog', :on => :member
      resources :images
    end
  end

  # search routes
  get     'search'                                  => 'search#results',  :as => 'search'

  # orders routes
  match 'orders/new'                                => 'orders#new'
  match 'orders/create'                             => 'orders#update'
  post 'orders/fulfill'                             => 'orders#fulfill'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def results
    query = CGI::escape(params[:q])
    page  = params[:page].blank? ? 1 : CGI::escape(params[:page]).to_i
    @search = Hash.from_xml(open("http://beta.korduroy.tv:8080/searchblox/servlet/SearchServlet?col=4&query=#{query}&page=#{page}").read)
    @results        = @search['searchdoc']['results']['result']
    @current_page   = @search['searchdoc']['results']['currentpage'].to_i
    @last_page      = @search['searchdoc']['results']['lastpage'].to_i
    @hits           = @search['searchdoc']['results']['hits'].to_i
    @previous_page  = @current_page - 1
    @next_page      = @current_page + 1
  end
end

app/views/search/results.html.erb
<%- title "Search Results" %>

<section id="search-results">
	<header id="contentHeader">
		<h1>Search Results for: <em><%= params[:q] %></em></h1>
	</header>
	
	<h2 class="results-count"><%= @search['searchdoc']['results']['hits'] %> total results</h2>
	
	<% if @hits == 0 %>
		<article>
			<h2>Sorry&hellip; No results found.</h2>
			<p>Please try another search.</p>
		</article>
	<% elsif @hits == 1 %>
		<article>
			<h2><%= link_to @search['searchdoc']['results']['result']['title'], @search['searchdoc']['results']['result']['url'] %></h2>
			<p><%= @search['searchdoc']['results']['result']['description'] %></p>
		</article>
	<% else %>

		<% @search['searchdoc']['results']['result'].each do |result| %>
			<article>
				<h2><%= link_to result['title'], result['url'] %></h2>
				<p><%= result['description'] %></p>
			</article>
		<% end %>
	
	<% end %>
	
	<nav class="pagination">
		<span class="prev"><%= link_to '‹ back', search_path(:q => params[:q], :page => @previous_page) unless @previous_page < 1 %></span>
		<span class="page-count">Page <%= @current_page %> of <%= @last_page %></span>
		<span class="next"><%= link_to 'next ›', search_path(:q => params[:q], :page => @next_page) unless @next_page > @last_page %></span>
	</nav>
</section>

app/views/search/results.html.haml
- title "Search Results"
%section#search-results
  %header#contentHeader
    %h1
      Search Results for:
      %em= params[:q]
  %h2.results-count
    = @search['searchdoc']['results']['hits']
    total results
  - if @hits == 0
    %article
      %h2 Sorry&hellip; No results found.
      %p Please try another search.
  - elsif @hits == 1
    %article
      %h2= link_to @search['searchdoc']['results']['result']['title'], @search['searchdoc']['results']['result']['url']
      %p= @search['searchdoc']['results']['result']['description']
  - else
    - @search['searchdoc']['results']['result'].each do |result|
      %article
        %h2= link_to result['title'], result['url']
        %p= result['description']
  %nav.pagination
    %span.prev= link_to '‹ back', search_path(:q => params[:q], :page => @previous_page) unless @previous_page < 1
    %span.page-count
      Page #{@current_page} of #{@last_page}
    %span.next= link_to 'next ›', search_path(:q => params[:q], :page => @next_page) unless @next_page > @last_page