config/routes.rb
KorduroyTv::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  # home routes
  root :to => "home#index"
  match 'home/add_newsletter'                       => 'home#add_newsletter'

  # blog routes
  get 'blog'                                        => 'blogs#index'
  get 'blog/rss'                                    => 'blogs#rss',              :as => 'blog_rss'
  get 'blog/:year/:slug'                            => 'blogs#show',             :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/, :as => 'main_blog'
  post 'blog/:year/:slug/comment'                   => 'blogs#comment',          :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/
  get 'blog/:year/:slug/comment'                    => 'blogs#show',             :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/
  get 'blog/:slug'                                  => 'blogs#category',         :slug => /[-a-zA-Z0-9]+/
  
  # shows routes
  resources :show_categories do
    resources :shows
  end
  get 'shows'                                       => 'shows#index'
  get 'shows/:slug'                                 => 'shows#category',         :slug => /[-a-zA-Z0-9]+/
  get 'shows/:slug/:show_slug'                      => 'shows#show',             :slug => /[-a-zA-Z0-9]+/, :show_slug => /[-a-zA-Z0-9]+/
  post 'shows/:slug/:show_slug/comment'             => 'shows#comment',          :slug => /[-a-zA-Z0-9]+/, :show_slug => /[-a-zA-Z0-9]+/
  get 'shows/:slug/:show_slug/comment'              => 'shows#show',             :slug => /[-a-zA-Z0-9]+/, :show_slug => /[-a-zA-Z0-9]+/
  post 'shows/:slug/:show_slug/rate'                => 'shows#rate',             :slug => /[-a-zA-Z0-9]+/, :show_slug => /[-a-zA-Z0-9]+/
  
  # makers routes
  get 'makers'                                      => 'makers#index'
  get 'makers/posts'                                => 'makers#index'
  get 'makers/list'                                 => 'makers#list'
  get 'makers/:slug'                                => 'makers#show',            :slug => /[-a-zA-Z0-9]+/,  :as => 'maker'
  get 'makers/:slug/blog/:year/:post_slug/:id'      => 'makers#blog',            :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/, :post_slug => /[-a-zA-Z0-9]+/, :id   => /[0-9]+/, :as => 'makers_blog'
  post 'makers/:slug/blog/:year/:post_slug/:id/comment' => 'makers#comment',     :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/, :post_slug => /[-a-zA-Z0-9]+/, :id   => /[0-9]+/
  get 'makers/:slug/blog/:year/:post_slug/:id/comment'  => 'makers#blog',        :year => /\d{4}/, :slug => /[-a-zA-Z0-9]+/, :post_slug => /[-a-zA-Z0-9]+/, :id   => /[0-9]+/
  get 'makers/:slug/rss'                            => 'makers#rss',             :slug => /[-a-zA-Z0-9]+/, :as => 'makers_rss'
  get 'makers/:slug/store'                          => 'makers#store',           :slug => /[-a-zA-Z0-9]+/
  get 'makers/:slug/store/:product'                 => 'makers#product',         :slug => /[-a-zA-Z0-9]+/, :product => /[0-9]+/
  get 'makers/:slug/gallery'                        => 'makers#gallery',         :slug => /[-a-zA-Z0-9]+/
  get 'makers/:slug/bio'                            => 'makers#bio',             :slug => /[-a-zA-Z0-9]+/
  get 'makers/category/:slug'                       => 'makers#category',        :slug => /[-a-zA-Z0-9]+/
  get 'makers/:slug/contact'                        => 'maker_contacts#new',     :slug => /[-a-zA-Z0-9]+/
  post 'makers/:slug/contact'                       => 'maker_contacts#create',  :slug => /[-a-zA-Z0-9]+/
  get 'makers/:slug/contact/thanks'                 => 'maker_contacts#thanks',  :slug => /[-a-zA-Z0-9]+/
  
  # the list routes
  resources :poll_categories do
    resources :polls
  end
  get 'the-list'                                    => 'polls#index'
  get 'the-list/:id'                                => 'polls#show',             :id   => /[0-9]+/
  post 'the-list/vote/:id'                          => 'polls#vote',             :id   => /[0-9]+/
  get 'the-list/:slug'                              => 'polls#category',         :slug => /[-a-zA-Z0-9]+/
  get 'the-list/results/:id'                        => 'polls#results',          :id   => /[0-9]+/
  post 'the-list/:id/comment'                       => 'polls#comment',          :id   => /[0-9]+/
  get 'the-list/:id/comment'                        => 'polls#show',             :id   => /[0-9]+/
  
  #store routes
  get 'store'                                       => 'stores#index'
  get 'store/:id'                                   => 'stores#show',            :id => /[0-9]+/
  get 'store/cart'                                  => 'stores#cart'

  #supporters routes
  resources :supporters, :only => [:index, :show]
  
  #cool routes
  get 'links'                                       => 'cool#index'
  
  #about routes
  get 'about'                                       => 'pages#about'
  get 'about/projects'                              => 'pages#projects'
  get 'about/big-shaka-club'                        => 'pages#club'
  get 'privacy'                                     => 'pages#privacy'
  get 'terms'                                       => 'pages#terms'
  get 'submissions'                                 => 'pages#submissions'
  get 'returns'                                     => 'pages#returns'
  get 'help'                                        => 'pages#help'
  get 'reef_x_cyrus_collab'                         => 'pages#reef_x_cyrus'
  get 'compassing'                                  => 'pages#compassing'

  #contact routes
  get 'contact'                                     => 'contacts#new'
  post 'contact'                                    => 'contacts#create'
  get 'contact/thanks'                              => 'contacts#thanks'

  #users routes
  devise_for :users do
    get 'users', :to => 'home#status', :as => :user_root
  end
  get 'status'                                      => 'home#status'
  
  #utilities routes
  get 'utilities/load_external_feeds'               => 'utilities#load_external_feeds', :constraints => {:ip => /127.0.0.1/}
  
  #makers admin : stores
  get    'makers_admin/stores'                      => 'makers_admin/stores#index'
  get    'makers_admin/stores/new'                  => 'makers_admin/stores#new'
  post   'makers_admin/stores/new_product'          => 'makers_admin/stores#new_product'
  get    'makers_admin/stores/:id/edit'             => 'makers_admin/stores#edit', :id => /[0-9]+/
  post   'makers_admin/stores/:id/update'           => 'makers_admin/stores#update', :id => /[0-9]+/
  post   'makers_admin/stores/:id/update_options'   => 'makers_admin/stores#update_options', :id => /[0-9]+/
  post   'makers_admin/stores/:id/variant/new'      => 'makers_admin/stores#new_variant', :id => /[0-9]+/
  post   'makers_admin/stores/:product_id/images'   => 'makers_admin/stores#images', :id => /[0-9]+/
  post   'makers_admin/stores/:id/variant/:variant_id/update' => 'makers_admin/stores#update_variant', :id => /[0-9]+/, :variant_id => /[0-9]+/
  delete 'makers_admin/stores/:id'                  => 'makers_admin/stores#delete', :id => /[0-9]+/
  delete 'makers_admin/stores/:product_id/images/:image_id' => 'makers_admin/stores#delete_image', :product_id => /[0-9]+/, :image_id   => /[0-9]+/
  delete 'makers_admin/stores/:product_id/variant/:variant_id' => 'makers_admin/stores#delete_variant', :product_id => /[0-9]+/, :variant_id   => /[0-9]+/
  get    'makers_admin/stores/orders'               => 'makers_admin/stores#orders'
  get    'makers_admin/stores/order/:id'            => 'makers_admin/stores#order', :id => /[0-9]+/
  
  #makers admin : images
  
  #makers admin : others
  namespace :makers_admin do
    resources :maker_photos, :maker_videos, :makers, :products
    resources :blogs do
      get 'reblog', :on => :member
      resources :images
    end
  end

  # search routes
  get     'search'                                  => 'search#results',  :as => 'search'

  # orders routes
  match 'orders/new'                                => 'orders#new'
  match 'orders/create'                             => 'orders#update'
  post 'orders/fulfill'                             => 'orders#fulfill'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ktv_posts = Blog.ktv_blog_posts.limit(5)

    @makers = Maker.where(:visible => true)
    @maker_posts = Blog.maker_blog_posts.limit(4)

    products_yaml =  Rails.cache.fetch('products', :expires_in => 30.minutes) do
      @products = ShopifyAPI::Product.find(:all, :params => {:collection_id => 4503832, :published_status => "published"}).to_yaml
    end

    @products = YAML::load(products_yaml)
    @featured_product = @products.first
    @featured_products = @products.sort_by{ rand }.slice(1..12)

    @polls = Poll.order("id DESC").limit(8).includes(:answers)
    @poll_home = true
    
    # scroller items
    @scroll_ktv_blog1 = @ktv_posts.first
    @scroll_ktv_blog2 = @ktv_posts.second
    @scroll_ktv_blog3 = @ktv_posts.third
    @scroll_shows = Show.limit(6).order('created_at DESC')
    @show1 = @scroll_shows[0]
    @show2 = @scroll_shows[1]
    @show3 = @scroll_shows[2]
    @scroll_maker_blog = @maker_posts.first
    @scroll_products = @products.sort_by{ rand }.slice(1..2)
  end

  def add_newsletter
    gb = Gibbon.new("837c3ca82822577ecf3f48bf67bcd9e0-us1")
    gb.throws_exceptions = false
    list = gb.lists({:filters => {:list_name => 'Korduroy.tv List'}})
    tmp = list.collect { |k, v| v }
    val =  tmp[1][0].collect{|k,v| v}
    resp = nil
    flag = true
    if(params[:newsletter] != "")
      resp = gb.list_subscribe({:id => val[0], :email_address => params[:newsletter].to_s})
    end

    if(resp == true)
      head :ok, :message => "Thank you for subscribing newsletter."
    else
      head :ok, :message => "You have already subscribed."
    end
  end
  
  def status
    render :layout => "plain"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_featured_slider.haml
#home-scroller
  #hs
    / latest show episode
    .panel.show{"data-showid" => @show1.vimeo}
      .panel-content
        %a{:href => "/shows/#{@show1.show_category.slug}/#{@show1.slug}"}
          .wrapper
            %img.featured-image{:alt => @show1.title, :src => @show1.thumbnail.gsub("_200.", "_960."), :width => "770"}
            .featured-copy
              = simple_format(sanitize (truncate_html @show1.description, :length => 250), :tags => %W(p))
          %h1
            %span.date New Show
            = @show1.title
            %span.category
              = @show1.show_category.title
          %img.badge{:alt => "Show", :src => "/assets/badge_show_large.png"}
    / latest ktv blog post
    .panel.blog
      .panel-content
        %a{:href => "/blog/#{@scroll_ktv_blog1.created_at.year}/#{@scroll_ktv_blog1.slug}"}
          .wrapper
            - if @scroll_ktv_blog1.post_image.blank?
              %img.featured-image{:alt => "", :src => "/assets/placeholder_xlarge.jpg"}
            - else
              %img.featured-image{:src => @scroll_ktv_blog1.post_image.xlarge}
            .featured-copy
              = simple_format(sanitize (truncate_html @scroll_ktv_blog1.content, :length => 300), :tags => %W(p))
          - unless @scroll_ktv_blog1.reblogged_at.blank?
            - @usr = @scroll_ktv_blog1.user
            - @mkr = @usr.maker
            %h1
              %span.date= l @scroll_ktv_blog1.created_at, :format => :poll
              %span.reblog Reblogged:
              = @scroll_ktv_blog1.title
            .related_maker
              %img.avatar{:src => @usr.avatar.large}
                %h2= @mkr.name
                %h3= @mkr.maker_category.name
          - else
            %h1
              %span.date= l @scroll_ktv_blog1.created_at, :format => :poll
              = @scroll_ktv_blog1.title
          %img.badge{:alt => "Blog", :src => "/assets/badge_blog_large.png"}
    / latest ktv blog post
    .panel.blog
      .panel-content
        %a{:href => "/blog/#{@scroll_ktv_blog2.created_at.year}/#{@scroll_ktv_blog2.slug}"}
          .wrapper
            - if @scroll_ktv_blog2.post_image.blank?
              %img.featured-image{:alt => "", :src => "/assets/placeholder_xlarge.jpg"}
            - else
              %img.featured-image{:src => @scroll_ktv_blog2.post_image.xlarge}
            .featured-copy
              = simple_format(sanitize (truncate_html @scroll_ktv_blog2.content, :length => 300), :tags => %W(p))
          - unless  @scroll_ktv_blog2.reblogged_at.blank?
            - @usr = @scroll_ktv_blog2.user
            - @mkr = @usr.maker
            %h1
              %span.date= l @scroll_ktv_blog2.created_at, :format => :poll
              %span.reblog Reblogged:
              = @scroll_ktv_blog2.title
            .related_maker
              %img.avatar{:src => @usr.avatar.large}
                %h2= @mkr.name
                %h3= @mkr.maker_category.name
          - else
            %h1
              %span.date= l @scroll_ktv_blog2.created_at, :format => :poll
              = @scroll_ktv_blog2.title
          %img.badge{:alt => "Blog", :src => "/assets/badge_blog_large.png"}
    / Latest Product
    - unless @scroll_makers.blank?
      / maker
      .panel.maker
        .panel-content
          %a{:href => "/makers/#{@scroll_makers.first.slug}"}
            .wrapper
              - if @scroll_makers.first.bio_image.blank?
                %img.featured-image{:alt => "", :src => "/assets/placeholder_xlarge.jpg"}
              - else
                %img.featured-image{:src => @scroll_makers.first.bio_image.xlarge}
              .featured-copy
                = simple_format(sanitize (truncate_html @scroll_makers.first.bio, :length => 300), :tags => %W(p))
            %h1= @scroll_makers.first.name
            %img.badge{:alt => "Maker", :src => "/assets/badge_maker_large.png"}
    - unless @scroll_products.blank?
      / product
      .panel.product
        .panel-content
          %a{:href => "/store/#{@scroll_products.first.id}"}
            .wrapper
              - if @scroll_products.first.images.blank?
                %img.featured-image{:alt => "", :src => "/assets/placeholder_xlarge.jpg"}
              - else
                %img.featured-image{:src => @scroll_products.first.images.first.src}
              .featured-copy
                = simple_format(sanitize (truncate_html @scroll_products.first.body_html, :length => 300), :tags => %W(p))
            %h1
              = @scroll_products.first.title
              %span.price
                $#{@scroll_products.first.price_range}
            %img.badge{:alt => "Store", :src => "/assets/badge_store_large.png"}
    / Show 2
    - unless @show2.blank?
      / latest show episode
      .panel.show{"data-showid" => @show2.vimeo}
        .panel-content
          %a{:href => "/shows/#{@show2.show_category.slug}/#{@show2.slug}"}
            .wrapper
              %img.featured-image{:alt => @show2.title, :src => @show2.thumbnail.gsub("_200.", "_960."), :width => "770"}
              .featured-copy
                = simple_format(sanitize (truncate_html @show2.description, :length => 250), :tags => %W(p))
            %h1
              = @show2.title
              %span.category
                = @show2.show_category.title
            %img.badge{:alt => "Show", :src => "/assets/badge_show_large.png"}
    - unless @scroll_ktv_blog3.blank?
      / latest ktv blog post
      .panel.blog
        .panel-content
          %a{:href => "/blog/#{@scroll_ktv_blog3.created_at.year}/#{@scroll_ktv_blog3.slug}"}
            .wrapper
              - if @scroll_ktv_blog3.post_image.blank?
                %img.featured-image{:alt => "", :src => "/assets/placeholder_xlarge.jpg"}
              - else
                %img.featured-image{:src => @scroll_ktv_blog3.post_image.xlarge}
              .featured-copy
                = simple_format(sanitize (truncate_html @scroll_ktv_blog3.content, :length => 300), :tags => %W(p))
            - unless @scroll_ktv_blog3.reblogged_at.blank?
              - @usr = @scroll_ktv_blog3.user
              - @mkr = @usr.maker
              %h1
                %span.date= l @scroll_ktv_blog3.created_at, :format => :poll
                %span.reblog Reblogged:
                = @scroll_ktv_blog3.title
              .related_maker
                %img.avatar{:src => @usr.avatar.large}
                  %h2= @mkr.name
                  %h3= @mkr.maker_category.name
            - else
              %h1
                %span.date= l @scroll_ktv_blog3.created_at, :format => :poll
                = @scroll_ktv_blog3.title
            %img.badge{:alt => "Blog", :src => "/assets/badge_blog_large.png"}

      / Maker Post should be disabled, but wanted to preserve the code
      - unless @scroll_maker_blog.blank?
        / latest maker post
        .panel.blog
          .panel-content
            %a{:href => "/makers/#{@scroll_maker_blog.user.maker.slug}/blog/#{@scroll_maker_blog.created_at.year}/#{@scroll_maker_blog.slug}/#{@scroll_maker_blog.id}"}
              .wrapper
                - if @scroll_maker_blog.post_image.blank?
                  - if @scroll_maker_blog.user.maker.bio_image.blank?
                    %img.featured-image{:src => "/assets/placeholder_xlarge.jpg"}
                  - else
                    %img.featured-image{:src => @scroll_maker_blog.user.maker.bio_image.xlarge}
                - else
                  %img.featured-image{:src => @scroll_maker_blog.post_image.xlarge}
                .featured-copy
                  = simple_format(sanitize (truncate_html @scroll_maker_blog.content, :length => 300), :tags => %W(p))
              %h1
                %span.date= l @scroll_maker_blog.created_at, :format => :poll
                = @scroll_maker_blog.title
              %img.badge{:alt => "Blog", :src => "/assets/badge_blog_large.png"}
      - unless @show3.blank?
        / latest show episode
        #latestShow3.panel.show{"data-showid" => @show3.vimeo}
          .panel-content
            %a{:href => "/shows/#{@show3.show_category.slug}/#{@show3.slug}"}
              .wrapper
                %img.featured-image{:alt => @show3.title, :src => @show3.thumbnail.gsub("_200.", "_960."), :width => "770"}
                .featured-copy
                  = simple_format(sanitize (truncate_html @show3.description, :length => 250), :tags => %W(p))
              %h1
                = @show3.title
                %span.category= @show3.show_category.title
              %img.badge{:alt => "Show", :src => "/assets/badge_show_large.png"}

  %a#hsPrev{:href => "#"} Previous
  %a#hsNext{:href => "#"} Next
  #hs-pag.pagination

app/views/home/index.html.haml
%section#featured-content.row.clearfix
  .three-fourths-column
    = render :partial => 'featured_slider'
  .one-fourth-column
    .featured-campaign.first
      = link_to image_tag( 'campaigns/compassing_banner.jpg'), compassing_path
    .featured-campaign
      = link_to image_tag( 'campaigns/show_us_your_quiver.jpg'), "http://showusyourquiver.com/", :target => "_blank"

%section#show-thumbs.row.clearfix
  .full-width-column
    .horizontal-stitch
    %header.clearfix
      %h1
        = link_to 'shows', shows_path
      %p.viewAll
        = link_to 'view all shows', shows_path
    %ul.shows
      - @scroll_shows.each do |show|
        %li.show
          %a{:href => "/shows/#{show.category.slug}/#{show.slug}"}
            %img.show-thumb{:alt => "", :src => show.thumbnail}
              %h2.show-title= show.title
    .horizontal-stitch

%section#blog-posts.row.clearfix
  .full-width-column
    %header.clearfix
      %h1
        = link_to 'blog', blog_path
      %p.viewAll
        = link_to 'view all posts', blog_path
    .blog-articles
      - @ktv_posts.each do |post|
        %article.clearfix
          .blog-image
            %a{:href => blog_path() + "/" + (l post.created_at, :format => :post_year) + "/" + post.slug}
              %img.postImage{:alt => post.title, :src => post_img = post.post_image.blank? ? "/assets/placeholder_blog_thumbnail.jpg" : post.post_image.small}/
          .blog-content
            - unless post.reblogged_at.blank?
              - @usr = post.user
              - @mkr = @usr.maker
              %h2
                %a{:href => blog_path() + "/" + (l post.created_at, :format => :post_year) + "/" + post.slug}
                  %span.reblog Reblogged:
                  = post.title
              .meta
                .posted-date
                  Posted on #{l post.created_at, :format => :post}
                .author
                  %a{:href => "/makers/#{@mkr.slug}"}
                    %img.avatar{:src => avatar = post.user.avatar.micro.blank? ? "/assets/avatar_micro.png" : post.user.avatar.micro}
                      = @mkr.name
            - else
              %h2
                %a{:href => blog_path() + "/" + (l post.created_at, :format => :post_year) + "/" + post.slug}= post.title
              .meta
                .posted-date
                  Posted on #{l post.created_at, :format => :post}
            .blog-article-text
              = simple_format(truncate(strip_tags(post.content), :length => 400, :separator => ' '))
              %p.moreLink= link_to "More...", blog_path() + "/" + (l post.created_at, :format => :post_year) + "/" + post.slug

app/views/home/status.html.haml
#status-message
  %header#modalHeader
    %h1
      Aloha, #{current_user.first_name}
  #status
    %p.notice= notice
    %p.alert= alert